server {
    listen 127.0.0.1:8082;
    server_name wp02.ernu.sec;
    root /var/www/wp02;
    index index.php index.html;
    access_log /var/log/nginx/wp02-access.log;
    error_log /var/log/nginx/wp02-error.log warn;
    location / { try_files $uri $uri/ /index.php?$args; }
    location = /xmlrpc.php { deny all; return 403; }
    location ~* /wp-content/uploads/.*\.php$ { deny all; return 403; }
    location ~ /\. { deny all; }
    location ~ /wp-config\.php { deny all; }
    location ~ \.php$ {
        try_files $uri =404;
        include fastcgi_params;
        fastcgi_pass unix:/run/php/php8.3-wp02.sock;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_read_timeout 300;
    }
}
