[wordpress-login]
enabled = true
filter = wordpress-login
logpath = /var/log/nginx/wp01-access.log
maxretry = 5
findtime = 600
bantime = 3600
port = http,https
action = ufw[name=wordpress-login, port="http,https", protocol=tcp]
