CREATE DATABASE IF NOT EXISTS npm CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS wp01_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS wp02_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'npm_user'@'localhost' IDENTIFIED BY 'CHANGE_ME_NPM_PASSWORD';
CREATE USER IF NOT EXISTS 'npm_user'@'172.30.10.%' IDENTIFIED BY 'CHANGE_ME_NPM_PASSWORD';
CREATE USER IF NOT EXISTS 'wp01_user'@'localhost' IDENTIFIED BY 'CHANGE_ME_WP01_PASSWORD';
CREATE USER IF NOT EXISTS 'wp02_user'@'localhost' IDENTIFIED BY 'CHANGE_ME_WP02_PASSWORD';

GRANT ALL PRIVILEGES ON npm.* TO 'npm_user'@'localhost';
GRANT ALL PRIVILEGES ON npm.* TO 'npm_user'@'172.30.10.%';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER ON wp01_db.* TO 'wp01_user'@'localhost';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER ON wp02_db.* TO 'wp02_user'@'localhost';
FLUSH PRIVILEGES;
