#!/usr/bin/env bash
set -euo pipefail
source .env
TMP_SQL=$(mktemp)
cat > "$TMP_SQL" <<SQL
CREATE DATABASE IF NOT EXISTS ${NPM_DB_NAME} CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS '${NPM_DB_USER}'@'localhost' IDENTIFIED BY '${NPM_DB_PASSWORD}';
CREATE USER IF NOT EXISTS '${NPM_DB_USER}'@'172.30.10.%' IDENTIFIED BY '${NPM_DB_PASSWORD}';
GRANT ALL PRIVILEGES ON ${NPM_DB_NAME}.* TO '${NPM_DB_USER}'@'localhost';
GRANT ALL PRIVILEGES ON ${NPM_DB_NAME}.* TO '${NPM_DB_USER}'@'172.30.10.%';

CREATE DATABASE IF NOT EXISTS ${WP01_DB_NAME} CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS '${WP01_DB_USER}'@'localhost' IDENTIFIED BY '${WP01_DB_PASSWORD}';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER ON ${WP01_DB_NAME}.* TO '${WP01_DB_USER}'@'localhost';
FLUSH PRIVILEGES;
SQL
mysql -u root -p < "$TMP_SQL"
rm -f "$TMP_SQL"
