[wp01]
user = wp01
group = wp01
listen = /run/php/php8.3-wp01.sock
listen.owner = www-data
listen.group = www-data
listen.mode = 0660
pm = dynamic
pm.max_children = 20
pm.start_servers = 5
pm.min_spare_servers = 3
pm.max_spare_servers = 10
pm.max_requests = 500
security.limit_extensions = .php
php_admin_value[open_basedir] = /var/www/wp01:/tmp
php_admin_value[error_log] = /var/log/php8.3-fpm/wp01-error.log
php_admin_flag[log_errors] = on
